# Generated by Django 5.1.1 on 2024-09-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_stars', '0002_remove_topic_course_remove_subtopic_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
