# Generated by Django 5.1.1 on 2024-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_stars', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
