# Generated by Django 5.1.1 on 2024-09-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five_stars', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isTeacher',
            new_name='is_teacher',
        ),
    ]
