# Generated by Django 5.1.1 on 2024-10-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='user_images/'),
        ),
    ]
