# Generated by Django 5.1.1 on 2024-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2015/11/15/07/47/geometry-1044090_1280.jpg'),
        ),
    ]
